services:
  plantix:
    build:
      context: ../../application/plantix
      dockerfile: Dockerfile
    container_name: plantix
    volumes:
      - ../../application/plantix:/app
    environment:
      # Base de datos
      MYSQL_DB_USERNAME: "${MYSQL_DB_USERNAME}"
      MYSQL_DB_PASSWORD: "${MYSQL_DB_PASSWORD}"
      MYSQL_DB_NAME: "${MYSQL_DB_NAME}"

      # Puerto (opcional, por defecto 8080)
      PORT: "${APP_PORT}"

      # SMTP Gmail (App Password 2FA)
      MAIL_USERNAME: "${EMAIL}"
      MAIL_PASSWORD: "${APP_PASSWORD}"
      ALERT_DEFAULT_RECIPIENTS: "${EMAIL}"

      # MQTT del stack docker
      MQTT_URL: "tcp://broker-mosquitto:1883"
      MQTT_USERNAME: "${MQTT_USERNAME}"
      MQTT_PASSWORD: "${MQTT_PASSWORD}"

      # Devtools (opcional)
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
      SPRING_DEVTOOLS_LIVERELOAD_ENABLED: "true"
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      plantix-db:
        condition: service_started
      broker-mosquitto:
        condition: service_started

  plantix-db:
    image: mysql:8.0
    container_name: plantix-db
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_MYSQL_ROOT_PASSWORD}"
    restart: unless-stopped
    volumes:
      - plantix_db_data:/var/lib/mysql
      - ../../application/plantixDB:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  broker-mosquitto:
    image: eclipse-mosquitto
    container_name: broker-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ../../brokerMQTT/config:/mosquitto/config
      - ../../brokerMQTT/data:/mosquitto/data
      - ../../brokerMQTT/log:/mosquitto/log
    restart: unless-stopped

volumes:
  plantix_db_data:

