name: plantix-ci

on: 
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-24.04
    outputs:
      short_commit: ${{ steps.get_short_commit.outputs.short }}
    steps:
      - uses: actions/checkout@v4

      - name: Get short commit
        id: get_short_commit
        run: echo "short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Docker login
        run: |
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login \
          registry.eginartedelgado.tech \
          --username ${{ secrets.REGISTRY_USER }} \
          --password-stdin

      - name: Build Docker Image
        run: |
          docker build \
          -f application/plantix/Dockerfile.prod \
          -t registry.eginartedelgado.tech/plantix-app:${{ steps.get_short_commit.outputs.short }} \
          -t registry.eginartedelgado.tech/plantix-app:prod \
          application/plantix

      - name: Push Docker image
        run: |
          docker push registry.eginartedelgado.tech/plantix-app:${{ steps.get_short_commit.outputs.short }}
          docker push registry.eginartedelgado.tech/plantix-app:prod

  deploy:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/tmp
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/tmp/id_ed25519
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/tmp/known_hosts
          chmod 600 ~/tmp/id_ed25519
      
      - name: Deploy to server
        run: |
          ssh \
            -i ~/tmp/id_ed25519 \
            -o UserKnownHostsFile=~/tmp/known_hosts \
            -p ${{ secrets.SSH_PORT }} \
            ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
              set -e

              cd /srv/plantix

              echo ${{ secrets.REGISTRY_PASSWORD }} | docker login \
                registry.eginartedelgado.tech \
                --username ${{ secrets.REGISTRY_USER }} \
                --password-stdin

              docker compose pull plantix-app

              docker compose up -d
            "
            
